language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true

install:
  - travis_retry composer self-update

after-install:
  - travis_retry composer install --no-interaction --prefer-source
  
script:
  - phpunit tests/html/HtmlEntitiesTest