language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 5.6
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-source

before-script:
  - travis_retry composer update
  - travis_retry composer self-update

script:
  - php -r "include_once('./tests/Html/Bootstrap.php');"
  - phpunit --configuration phpunit.xml