language: php
php:
- 5.6
- 5.5
- 5.4
before_install:
- travis_retry composer self-update
install:
- travis_retry composer install --no-interaction
script: 
- phpunit --configuration phpunit.xml
- php SameTest.php